[package]
name = "go_lib"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[lib]
name = "go_lib"
crate-type = ["cdylib", "staticlib"]

[dependencies]
# Internal crates
# External crates
libc = { workspace = true }
