[package]
name = "core_lib"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[lib]
name = "core_lib"

[dependencies]
# No external dependencies - pure Rust core functionality
